config/routes.rb
Rails.application.routes.draw do

  resources :wishes
  
  resources :books
  resources :session
 
  resources :users
  resources :loans
  get 'session/new'

  get 'session/create'

  get 'session/destroy'
  get "welcome/menuAdmin"
  get "/visitors/about"
  get "welcome" => "welcome#index", :as => "welcome"
  get "visitors" => "visitors#index", :as => "visitors"
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create"
  get "signup" => "users#new", :as => "signup"
  
  if :logged_in?
    root :to => "welcome#index"
  else
    root :to => "visitors#index"
  end
  
 
  

=begin devise_scope :user do
   
     get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
    authenticated :user do
      root :to => 'welcome#index'
    end
    unauthenticated :user do
      root :to => 'visitors#index', as: :unauthenticated_root
    end
  end
  
=end
  

end

app/models/wish.rb
class Wish < ActiveRecord::Base
  validates_uniqueness_of :user_id, :scope => :book_id
  belongs_to :user
  belongs_to :book
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  respond_to :html

  def index

      @wishes = Wish.where( :user => current_user.id)
      @current_user = current_user
      respond_with(@wishes)
  end

  def show
    
    respond_with(@wish)
  end

  def new
    @wish = Wish.new
    respond_with(@wish)
  end

  def edit
  end

  def create
    @current_user = params[:user_id] 
    @wish = Wish.new
    @wish.user = User.find(params[:user_id])
    @wish.book = Book.find(params[:book_id])
    
     respond_to do |format|
      if @wish.save
       
        format.html { redirect_to books_path, notice: 'Book added to your wish list' }
      else
        format.html { redirect_to books_path, alert: 'Book already in your wish list' }
      end
  end
    
    
  
    
  end

  def update
    @wish.update(wish_params)
    respond_with(@wish)
  end

  def destroy
    @wish.destroy
    redirect_to wishes_path
  end

  private
    def set_wish
      @wish = Wish.find(params[:id])
    end

    def wish_params
      params.require(:wish).permit(:user_id, :book_id)
    end
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/wishes/_form.html.erb
<%= form_for(@wish) do |f| %>
  <% if @wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% @wish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br>
    <%= f.text_field :book_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishes/edit.html.erb
<h1>Editing wish</h1>

<%= render 'form' %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>

app/views/wishes/index.html.erb
<h1>Listing wishes</h1>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Wishes list</div>
  <% if @wishes.blank? %>
    <br>
    <br>
    <h3><%= 'No wishes in your list'%></h3>
    <% else %>
      <div class="table-responsive">
        <!-- Table -->
        <table class="table table.responsive table-hover">
          <thead>
            <tr>
              <th>User</th>
              <th>Book</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>

            <% @wishes.each do |wish| %>
              <tr>
                <td>
                  <%=wish.user.name %>
                </td>
                <td>
                  <%=wish.book.Title %>
                </td>

                <td>
                  <div class="btn-toolbar">
                    <!--<%= link_to "Show", wish, :class => "btn btn-success" %>
                    <%= link_to "Edit", edit_wish_path(wish), :class => "btn btn-warning" %>-->
                    <%=link_to 'Destroy', wish, :class=> "btn btn-primary btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                </td>
              </tr>

          </tbody>

        </table>

      </div>
      <% end %>
        <%end%>

</div>

<br>

app/views/wishes/new.html.erb
<h1>New wish</h1>

<%= render 'form' %>

<%= link_to 'Back', wishes_path %>

app/views/wishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @wish.user.name %>
</p>

<p>
  <strong>Book:</strong>
  <%= @wish.book.Title %>
</p>

<%= link_to 'Edit', edit_wish_path(@wish) %> |
<%= link_to 'Back', wishes_path %>