config/routes.rb
Rails.application.routes.draw do

  resources :wishes
  
  resources :books
  resources :session
 
  resources :users
  resources :loans
  get 'session/new'

  get 'session/create'

  get 'session/destroy'
  get "welcome/menuAdmin"
  get "/visitors/about"
  get "welcome" => "welcome#index", :as => "welcome"
  get "visitors" => "visitors#index", :as => "visitors"
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create"
  get "signup" => "users#new", :as => "signup"
  
  if :logged_in?
    root :to => "welcome#index"
  else
    root :to => "visitors#index"
  end
  
 
  

=begin devise_scope :user do
   
     get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
    authenticated :user do
      root :to => 'welcome#index'
    end
    unauthenticated :user do
      root :to => 'visitors#index', as: :unauthenticated_root
    end
  end
  
=end
  

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  validates_uniqueness_of :user_id, :scope => :book_id
  belongs_to :user
  belongs_to :book
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  respond_to :html

  def index
    @current_user = current_user
    if @current_user.role == 'reader'
      @loans = Loan.where(@loan.user => @current_user.id)
    else
    @loans = Loan.all
  end
    
    respond_with(@loans)
  end

  def show
    respond_with(@loan)
  end

  def new
    
    @books = Book.all
    @loan = Loan.new
    @users = User.where(:role => "reader")
    
    
  end

  def edit
  end

  def create
    @wloan = Loan.new(loan_params)
=begin
@loan.user = User.find(params[:user_id])
    @wish.book = Book.find(params[:book_id])
    @loan.physical = params[:physical]
    @loan.loandate = params[:loandate]
    @loan.loanreturn = params[:loanreturn]
    @loan.save
=end
  end

  def update
    @loan.update(loan_params)
    respond_with(@loan)
  end

  def destroy
    @loan.destroy
    respond_with(@loan)
  end

  private
    def set_loan
      @loan = Loan.find(params[:id])
    end

    def loan_params
      params.require(:loan).permit(:user_id, :book_id, :physical, :loandate , :loanreturn)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
 <%= f.select :user, @users.collect{ |c| [c.name, c]}%>
 <%= f.select :book_id, @books.collect{ |b| [b.Title, b.id]} %>
  </div>
  <div class="field">
    <%= f.label "Physical" %> <br />
    <%= f.check_box :physical %> <br />
</div>
  
  
  <div class="actions"><%= f.submit 'Add', class: "btn btn-lg btn-primary" %></div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<h1>Listing loans</h1>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Loans list</div>
<div class="table-responsive">
  <!-- Table -->
  <table class="table table.responsive table-hover">
    <thead>
           <tr>
      <th>User</th>
      <th>Book</th>
      <th>LoanDate</th>
     <th>LoanReturn</th>
     <th>Format</th>
      <th colspan="3"></th>
    </tr>
        </thead>
        <tbody>
          <% @loans.each do |loan| %>
         
             <tr>
              <td><%= loan.user.email %></td>
              <td><%= loan.book.Title %></td>
              <td><%= loan.loandate %></td>
              <td><%= loan.loanreturn %></td>
             <td><%= loan.physical %></td>
              <% if @current_user.role == 'admin' or @current_user.role == 'manager' %>
              <td>
                <div class="btn-toolbar">
                  <%= link_to "Show", loan, :class => "btn btn-success" %>
                  <%= link_to "Edit", edit_loan_path(loan), :class => "btn btn-warning" %>
                   <%= link_to 'Destroy', loan, :class => "btn btn-primary btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </td>
               <% end %>
            </tr>
            <% end %>
        </tbody>
    
  </table>
  </div>
</div>


<!--<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th>Loandate</th>
      <th>Loanreturn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.user %></td>
        <td><%= loan.book %></td>
        <td><%= loan.loandate %></td>
        <td><%= loan.loanreturn %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>-->

<br>

<%= link_to 'New Loan', new_loan_path, :class => "btn btn-primary btn-info" %>

app/views/loans/new.html.erb
<h1>Choose the user:</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @loan.user.email %>
</p>

<p>
  <strong>Book:</strong>
  <%= @loan.book %>
</p>

<p>
  <strong>Loandate:</strong>
  <%= @loan.loandate %>
</p>

<p>
  <strong>Loanreturn:</strong>
  <%= @loan.loanreturn %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>